services:
  lp:
    image: chainfliplabs/chainflip-lp-api:1.4
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    volumes:
      - .:/etc/chainflip/keys
    entrypoint:
      - /usr/local/bin/chainflip-lp-api
    command:
      - --state_chain.ws_endpoint=wss://mainnet-rpc.chainflip.io:443

  cf-lp:
    image: ghcr.io/cumpsd/chainflip-lp:v8.0.38
    pull_policy: always
    restart: unless-stopped
    user: root
    working_dir: "/app"
    environment:
      - DOTNET_PRINT_TELEMETRY_MESSAGE=false
      - Bot__EnableLp=true
      - Bot__QueryDelay=60000
      - Bot__NodeRpcUrl=https://mainnet-rpc.chainflip.io
      - Bot__LpRpcUrl=http://lp
      - Bot__LpAccount=cF_YOUR_LP_ACCOUNT
      - Bot__DustOrderSize=5
      - Bot__MinimumOrderSize=20
      - Bot__TelegramChannelId=-1001234567890
      - Bot__Pools__0__Chain=Ethereum
      - Bot__Pools__0__Asset=USDT
      - Bot__Pools__0__Slice=80
      - Bot__Pools__0__MinBuyTick=0
      - Bot__Pools__0__MaxBuyTick=1
      - Bot__Pools__0__MinSellTick=0
      - Bot__Pools__0__MaxSellTick=-1
      - Bot__Pools__1__Chain=Arbitrum
      - Bot__Pools__1__Asset=USDC
      - Bot__Pools__1__Slice=20
      - Bot__Pools__1__MinBuyTick=0
      - Bot__Pools__1__MaxBuyTick=1
      - Bot__Pools__1__MinSellTick=0
      - Bot__Pools__1__MaxSellTick=-1
      - Serilog__MinimumLevel__Override__ChainflipLp=Information
    depends_on:
      - lp
